services:
    sonata.admin.produit:
        class: Admin\AdminBundle\Admin\ProduitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Produit" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Produit
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
    sonata.admin.commande:
        class: Admin\AdminBundle\Admin\CommandeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Commande" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Commande
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]          